source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/thinkaboutiter/SimpleLogger.git"

# Uncomment this line to define a global platform for your project
platform :ios, "9.0"

target "FClient" do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FClient
  pod "SnapKit", "~> 0.20"
  pod "SimpleLogger", "0.1.9"
  pod "MagicalRecord", "~> 2.3.2"

end
